### PR TITLE
Replaced DROP DATABASE by dropdb

### PR DESCRIPTION
**Pull request by ziggurat**

### CODE REVIEW

**Comment by ziggurat** [comment]
This should fix https://github.com/lotus/model/issues/209

**Comment by ericboehs** [comment]
I don't think this will use the database user specified in the connection url.

**Comment by ericboehs** [comment]
I think we just need to change it to
```ruby
new_connection.run "DROP DATABASE IF EXISTS `#{ database }`"
```

It does seem odd though that it doesn't think the database exists in the case of #209. Is `database` have the correct value? Are the double quotes instead of back ticks throwing it off?

**Comment by ziggurat** [comment]
I can confirm it won't delete the DB even if it exists, I have not checked the double quotes. I made that change because all other commands are being executed using the CLI tools from postgres and not the SQL command. Regarding your comment on using the user, the environment variables are set before running the commands, setting user, host, port and pass. And then those environment variables are being picked up by the createdb command as stated in the documentation:

> PGHOST
PGPORT
PGUSER
Default connection parameters
This utility, like most other PostgreSQL utilities, also uses the environment variables supported by libpq

Nevertheless, I will chek the double quotes.
Thanks!

**Comment by ziggurat** [comment]
Had no luck changing the quotes.

**Comment by AlfonsoUceda** [comment]
@ziggurat did you try with @ericboehs suggestion? http://www.postgresql.org/docs/9.1/static/sql-dropdatabase.html

**Comment by ziggurat** [comment]
@AlfonsoUceda yes, I tried that solution without luck. I have some time today, I will try again and let you know.

**Comment by ziggurat** [comment]
@ericboehs @AlfonsoUceda any ideas? As stated in the posgres documentation, we can't run the DROP command connected to the DB we want to drop. So I think alternatives are using a different connection to run the DROP command or using the dropdb postgres script.

**Comment by joneslee85** [comment]
@ziggurat can you please add test? I am not convinced till we have test

**Comment by ziggurat** [comment]
I am not sure what test to add, tests are creating and droping dbs succesfully using the migrators. There is 100% coverage for the modified adapter. Sorry for being a pain, it's my first time collaborating in an open source project.

**Comment by joneslee85** [comment]
@ziggurat I've just done a hand-test and I could be able to drop DB without the needs of this patch.

**Comment by joneslee85** [comment]
@ziggurat I close this ticket now because your edge case will never happen, because we instantiate new connection for every drop query and this connection does not connect to the database

**Comment by joneslee85** [comment]
I amended your PR to keep the old behaviour

https://github.com/lotus/model/pull/223/files

**Pull request closed without merging**
