### PR TITLE
fix sqlite tests

### PR DESCRIPTION
**Pull request by aderyabin**
Attempt to fix sqlite test in Travis.

### CODE REVIEW

**Comment by joneslee85** [comment]
@aderyabin the best way is to get in touch with Travis and ask for access to their CI box, I did it in the past

**Comment by hlegius** [comment]
@aderyabin jodosha pushed to master today a commit which may fix your issues with sqlite. Did you test it already?

**Comment by aderyabin** [comment]
@hlegius Not yet.

**Comment by aderyabin** [comment]
@hlegius Yes, great job!

**Comment by jodosha** [comment]
@aderyabin :smile:

**Pull request closed without merging**
