### PR TITLE
Drop support for mysql adapter in favour of mysql2 adapter

### PR DESCRIPTION
**Pull request by joneslee85**
Sequel supports both mysql and mysql2, in majority of cases mysql2 are opted to mysql. By adopting one mysql engine, I think it would reduce the maintenance for the team and enhances the consistency

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
Why this change? is it better mysql2 than mysql?

to me :+1:

**Comment by brennovich** [comment]
@AlfonsoUceda yep, it is. `mysql` is outdated and I don't even know if it run against Ruby 2.2 http://stackoverflow.com/questions/5411551/what-the-difference-between-mysql-and-mysql2-gem

**Comment by jodosha** [comment]
@joneslee85 While `mysql2` is better than `mysql` this is true only for MRI. With the goal in mind to support JRuby, the jdbc adapter doesn't recognize the `mysql2://` scheme for URL and raises an exception:

```
  1) Error:
Lotus::Model::Adapters::SqlAdapter::#initialize#test_0004_changes the URI of mysql:// to mysql2://:
Lotus::Model::Adapters::DatabaseAdapterNotFound: LoadError: no such file to load -- mysql2
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/sql_adapter.rb:264:in `connect'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/sql_adapter.rb:47:in `initialize'
    /Users/luca/Code/lotus/model/test/model/adapters/sql_adapter_test.rb:83:in `block in test_0004_changes the URI of mysql:// to mysql2://'
```

I'm gonna to revert this change for JRuby compat and to leave freedom to devs to use the low level adapter they need. That being said, `mysql2` must be the one that we promote, like we did with #331. Good job :clap:

**Comment by brennovich** [comment]
@jodosha please don't revert it. We need to treat as a special case, because neither `mysql` nor `mysql` works for jruby, they are MRI only. We need to ensure that `jdbc-mysql` will be used for jruby

**Comment by jodosha** [comment]
@brennovich Don't you think it's up to the devs to provide the right URI in their `.env` files?

**Comment by brennovich** [comment]
You're are right, what I said in my previous comment applies only for lotus generators, I think ;)

**Comment by joneslee85** [comment]
@jodosha fair point, please revert it

**Comment by jodosha** [comment]
@joneslee85 @brennovich I reverted and removed GH milestone.

**Pull request merged**
