### PR TITLE
Make Respository.execute private (issue #190.)

### PR DESCRIPTION
**Pull request by mjbellantoni**
Makes this method private and removes the associated tests.

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
@mjbellantoni ok but you have to test you can't call something like `BookRepository.execute()` and you are able to call execute inside a repository method like:
```ruby
class BookRepository
  include Lotus::Repository
  
  def aggregated
    execute()
  end
```

**Comment by mjbellantoni** [comment]
Can you drop a pointer to an existing test which test something similar?  I'm not that deeply familiar with the framework.  (I'm also not in the habit of writing tests for private methods.)

**Comment by AlfonsoUceda** [comment]
one test can be that you can't call execute like `BookRepository.execute()` another can be use execute inside the example above and assert the response.
```ruby
class BookRepository
  include Lotus::Repository

  def aggregated
    execute("SELECT * FROM books;")
  end
end
```
You can assert that SELECT

**Comment by jodosha** [comment]
@mjbellantoni I think @AlfonsoUceda Is right. Repository has a bunch of **private methods marked as public API**. The reason is that we don't want to leak finders outside of the repository.

The following code isn't possible with Lotus::Model.

```ruby
BookRepository.where(author_id: author.id)
```

This because we want to force devs to define explicit API for their domain model:

```ruby
class BookRepository
  include Lotus::Repository

  def self.by_author(author)
    query do
      where(author_id: author.id)
    end
  end
end
```

Technically, this is a private method, and in general you shouldn't write tests for them. But this is meant to be used by devs (public API), so it deserves to be covered with tests.

Can you please restore and rework them, according to the new semantic? Thank you very much.

**Comment by mjbellantoni** [comment]
I've added the test back in.  There were a couple of places to put these into the test suite.  I left them in the same locations where they were originally.  (The other option was to do something similar to the "querying" test.)

Also, I added a the method `ArticleRepository.aggregate` to that fixture class.  I originally tried adding it to an anonymous subclass of `ArticleRepository` (using `Class.new`) but the class instance variable is not available to subclasses.  (I much prefer that pattern in test suites.)

Looking forward to your feedback!

**Comment by jodosha** [comment]
@mjbellantoni It looks good now. Merged, thank you! :+1:

**Pull request merged**
