### PR TITLE
Implement SQL inner join

### LINKED ISSUE #34: SQL Joins
Add support to SQL joins to `Sql::Adapter` and `Sql::Query`.

### PR DESCRIPTION
**Pull request by jodosha**
## SQL joins

Given the following mapping:

```ruby
Lotus::Model::Mapper.new do
  collection :users do
    entity User

    attribute :id,   Integer
    attribute :country_id, Integer
    attribute :name, String
    attribute :age, Integer
  end

  collection :devices do
    entity Device

    attribute :id, Integer
    attribute :u_id, Integer
  end

  collection :orders do
    entity Order

    attribute :id,      Integer
    attribute :user_id, Integer
    attribute :total,   Integer
  end

  collection :ages do
    entity Age

    attribute :id, Integer
    attribute :value, Integer
    attribute :label, String
  end

  collection :countries do
    entity Country

    attribute :id, Integer, as: :country_id
    attribute :code, String
  end
end
```

#### Default

```ruby
class OrderRepository
  include Lotus::Repository

  def self.foo
    query do
      join(:users)
    end
  end
end
```

```sql
SELECT `orders`.* FROM `orders` INNER JOIN `users` ON (`users`.`id` = `orders`.`user_id`)
```

#### Specify key

```ruby
class UserRepository
  include Lotus::Repository

  def self.foo
    query do
      join(:countries, key: :country_id)
    end
  end
end
```

```sql
SELECT `users`.* FROM `users` INNER JOIN `countries` ON (`countries`.`country_id` = `users`.`country_id`)
```

#### Specify foreign key

```ruby
class DeviceRepository
  include Lotus::Repository

  def self.foo
    query do
      join(:users, foreign_key: :u_id)
    end
  end
end
```

```sql
SELECT `devices`.* FROM `devices` INNER JOIN `users` ON (`users`.`id` = `devices`.`u_id`)
```

#### Specify both key and foreign key

```ruby
class UserRepository
  include Lotus::Repository

  def self.foo
    query do
      join(:ages, key: :value, foreign_key: :age)
    end
  end
end
```

```sql
SELECT `users`.* FROM `users` INNER JOIN `ages` ON (`ages`.`value` = `users`.`age`)
```

Closes #34

### CODE REVIEW

**Comment by jodosha** [comment]
@AlfonsoUceda I had to postpone this because of lack of time before `lotusrb-0.2.0`.

**Comment by cgarvis** [comment]
:+1:

**Comment by mvader** [comment]
Is this going to be merged soon? It'd be really helpful to have that feature.

**Comment by vladislavpauk** [comment]
Hi @jodosha, could you tell me how soon the code will be merged with the master branch?

**Comment by AlfonsoUceda** [comment]
Closed by #228

**Pull request closed without merging**
